import "./css/globals.css";
import type { Metadata } from "next";
import Header from "@/components/Header";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="font-bodyFont w-full bg-main-bg text-darkText bg-container">
        <Header />
        <NavBar />
        <div className="max-w-screen-xl mx-auto px-4">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
